### ISSUE TITLE
合并前端代码中的问题

### ISSUE THREAD

**Issue by uicestone** [uicestone/YiZhou-Studio#11]
1. 翻页机制现在是如何的，数据如何加载，后端如何配合？
2. 有许多页面并无翻页功能，按钮仍然保留，是否是错误？
3. content-2, content-3cols, content-closeup三个文件如何使用？

**Comment by uicestone** [comment]
@Natt7 @JennieJi 来看看

**Comment by Natt7** [comment]
列表页需要翻页的，然后内容页做的三个都是模板，应该是直接发文章的时候用的吧。有些页没有翻页是因为内容还不够多一页就够了。

**Comment by JennieJi** [comment]
@Natt7 列表翻页的效果应该是照原来的吧？文章就算不上翻页了，得刷新整张页面
@uicestone ：
2. 照Natt的话说，现在没有翻页，以后还会有翻页的－ ＝
3. 嘛，客户坚持要页面模版，我不知道你那边要怎么搞。

**Comment by Natt7** [comment]
@JennieJi 还是每次翻页都刷新吧，因为以后可能会有更多的文章，如果翻页不刷新载入的时间会比较长。

**Comment by JennieJi** [comment]
@uicestone 那就直接做成link，只要没有paging-wrapper这个class就不会触发js
