### ISSUE TITLE
文章列表页应该只有两个项目

### ISSUE THREAD

**Issue by Natt7** [uicestone/YiZhou-Studio#18]
列表页每页应该只有两个项目。

**Comment by uicestone** [comment]
@JennieJi 分页怎么说？是我全部打出来前端分，还是每次翻页后端请求？如果是后者，我们要定一下API。

**Comment by JennieJi** [comment]
@uicestone 根据 @Natt7 说的，现在完全不需要前端翻页，直接做链接刷新整个页面就好了。我记得我已经禁用掉初始化前端翻页的代码。

**Comment by Natt7** [comment]
我考虑的是以后如果文章多了，载入的时间会比较长，刷新的话可以规避这个问题。 如果你们觉得全部打出来也可以的话，那当然是全部打出来体验更好一些。
