### ISSUE TITLE
替换contact us的地图图片

### ISSUE THREAD

**Issue by Natt7** [uicestone/YiZhou-Studio#21]
![contact us](https://cloud.githubusercontent.com/assets/5966927/6779773/5dbce602-d19a-11e4-9aee-40b91a5d080f.jpg)

**Comment by JennieJi** [comment]
@Natt7 目前做的根据屏幕尺寸大小只截取显示地图最中间那块的图片，没问题吗

**Comment by Natt7** [comment]
用这张新的图，然后宽度你来确定，高度auto，不要截取。
